### PR TITLE
fix: expired user token

### LINKED ISSUE #198: [Bug]: expired user token
### Expected Behavior
Question/expected result.
What to do when user token is expired but page was not reload?

### Actual Behavior
when u stay a long in account and try to change address u r getting error in methods save, update

request to api/magento/createCustomerAddress
getting an error in console
useAddresses/save TypeError: Cannot read properties of undefined (reading 'createCustomerAddress')

const {
remove,
update,
save,
error: errorAddresses
} = useAddresses();
and in error 

width=200,height=183

### Possible Solution
1. Handle token expiration
1. Redirect to the homepage
1. Display a notification about logging out because of inactivity
1. Remove the "Remember me" checkbox from the login popup
1. Update the docs and stand out that we use default Magento process

### Steps to reproduce
1. Log in. to customer account
1. got to my account
1. go to address details
1. click: change address
1. Wait for session expired, or remove vsf-customer cookie
1. Submit form
1. Observe the error

### What version of Magento 2 integration are you using?
2.4.3

### What version of Node.js are you using?
v14.17.5

### What browser (and version) are you using?
Chrome Version 94.0.4606.71 (Official Build) (x86_64)

### What operating system (and version) are you using?
macOS Version 11.6 (20G165)

### Relevant log output
_No response_

### Code of Conduct
* \[x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by KevinGorjan**
Fixes #198 

## Description
When the customer token is expired, it will log out the user and redirect the user to the home page.
A notification message will be displayed

## How Has This Been Tested?

* Create an account
* Log in to your account
* Enter your account (/my-account)
* Wait until the session is expired (by default this is 4h)
* When the customer token is expired, you will be redirected to the home page

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Frodigo — CHANGES_REQUESTED** [review]

File: packages/theme/plugins/token-expired.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+  let once = true;
+  app.$vsf.$magento.client.interceptors.response.use(async (r) => {
+    if (r.data.message === 'The current customer isn\'t authorized.' && once) {
+      once = false;
+      const { send: sendNotification } = useUiNotification();
+
+      const apiState = app.$vsf.$magento.config.state;
+      await apiState.setCustomerToken(null);
+      await apiState.setCartId(null);
+      // ToDo :: Clear Cart items
```
[the remark this answers is not in the document]
Comment (KevinGorjan) [reply packages/theme/plugins/token-expired.js:13]: No, I can’t complete this task because for some reason we can’t use composables in plugins or middlewares.
The application crashes.

File: packages/theme/components/LoginModal.vue [hunk 2]
```diff
@@ -56,13 +56,15 @@
...
+            <!--
             <SfCheckbox
               v-model="rememberMe"
               v-e2e="'login-modal-remember-me'"
               name="remember-me"
               label="Remember me"
               class="form__element checkbox"
             />
+            -->
             <div v-if="error.login">
```
Comment (bloodf) [inline packages/theme/components/LoginModal.vue:68]:
```suggestion
            <div v-if="error.login">
```

File: packages/theme/plugins/token-expired.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (bloodf) [reply packages/theme/plugins/token-expired.js:13]: @Frodigo the problem with Composables in plugins is due to composition-api :(

Until Vue 3 is 100% we need to do some "gambiarras" 

Brazilian slang for those adaptations :P

**Review by bloodf — CHANGES_REQUESTED** [review]

File: packages/theme/composables/useUiNotification/index.ts [hunk 3]
```diff
@@ -22,13 +23,18 @@ const maxVisibleNotifications = 3;
 const timeToLive = 3000;
 
 const useUiNotification = () => {
+  const { app } = useContext();
+  const cookieMessage: UiNotification = app.$cookies.get(cookieNames.messageCookieName);
```
Comment (bartoszherba) [inline packages/theme/composables/useUiNotification/index.ts:27]: Can we translate this message? Or add improvement to translate all messages?

Comment (bartoszherba) [reply packages/theme/composables/useUiNotification/index.ts:27]: Also, please add cookie message to a translation list in lang.

File: packages/theme/plugins/token-expired.js [hunk 4]
```diff
@@ -0,0 +1,26 @@
+import cookieNames from '~/enums/cookieNameEnum';
+
+export default ({ app, redirect }) => {
```
Comment (bartoszherba) [inline packages/theme/plugins/token-expired.js:3]: Can we write UT for this plugin?

File: packages/theme/composables/useUiNotification/index.ts (hunk 3 above)
Comment (Frodigo) [reply packages/theme/composables/useUiNotification/index.ts:27]: Done

File: packages/theme/plugins/token-expired.js (hunk 4 above)
Comment (Frodigo) [reply packages/theme/plugins/token-expired.js:3]: Tests added.

**Review by Frodigo — APPROVED** [review]

**Review by bartoszherba — DISMISSED** [review]

**Review by Frodigo — APPROVED** [review]

**Comment by Frodigo** [comment]
Hi, @bloodf can you review this one again?
