### PR TITLE
fix: fix a message about submitted review

### LINKED ISSUE #1226: Product Page - Missing toast with information that your review has been submitted
### Steps to reproduce

1. Open any product details page.
2. Hit "Add a review".
3. Add a review.

### Actual behavior

Toast with information that your review has been submitted is missing. Message text: "You submitted your review for moderation."

### Expected behavior
Toast should be displayed.

### Additional bug information
Reproduced with Chromium based browsers (Chrome, Edge), Safari and Firefox - both desktop and mobile.

### PR DESCRIPTION
**Pull request by sequensucks**
fix #1226

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
   <div>
     <div v-if="reviewSent && !error.addReview">
-      <p>Your review was submitted!</p>
+      <p>{{ $t('You submitted your review for moderation.') }}</p>
```
Comment (bartoszherba) [inline packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue:4]: This message is not appropriate because moderation is an optional setting in the Magento. We must add more generic, I think that the previous one was ok. Unfortunately there is no way to read the actual setting from Magento.

File: packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue [hunk 2]
```diff
@@ -102,10 +105,10 @@ export default defineComponent({
   setup(props, { emit }) {
     const { routeData } = usePageStore();
     const reviews = ref(null);
+    const isReviewsLoading = ref(true);
```
Comment (bartoszherba) [inline packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue:108]: How is this change address issue #1226? If this is a different problem, please create a separate PR to fix it.

**Review by bartoszherba — CHANGES_REQUESTED** [review]

File: packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue (hunk 2 above)
Comment (sequensucks) [reply packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue:108]: when we use a loading from useReview a list of reviews rerender when we are adding a new review.
And an actual result is a list of reviews, but we want to see a submitted message.

File: packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue (hunk 1 above)
Comment (sequensucks) [reply packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue:4]: The message from an issue
https://github.com/vuestorefront/magento2/issues/1226

We could create a new param(boolean) is_product_review_ moderation in the .env.

File: packages/theme/lang/en.js [hunk 3]
```diff
@@ -303,4 +303,5 @@ export default {
   "Payment date":"Payment date",
   "The user password was changed successfully updated!":"The user password was changed successfully updated!",
   "The user account data was successfully updated!":"The user account data was successfully updated!",
+  "You submitted your review for moderation.": "You submitted your review for moderation.",
```
Comment (bartoszherba) [inline packages/theme/lang/en.js:306]: Please, add the german translation.

File: packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue (hunk 1 above)
Comment (bartoszherba) [reply packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue:4]: Ok, let it be as it is. It does not hurt to say that the review will be moderated event if the moderation is disabled.

File: packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue (hunk 2 above)
Comment (bartoszherba) [reply packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue:108]: Ok.

**Review by bartoszherba — CHANGES_REQUESTED** [review]
Please, add german translation and we can move on.

**Comment by sequensucks** [comment]
@bartoszherba added from a google translate. I don't know german=)

**Review by bartoszherba — APPROVED** [review]

**Comment by bartoszherba** [comment]
@sequensucks Please, fix conflicts.

**Comment by sequensucks** [comment]
@bartoszherba merged a current develop branch

**Comment by bartoszherba** [comment]
@sequensucks Please, resolve conflicts.

**Comment by sequensucks** [comment]
@bartoszherba merged a current develop branch

**Comment by bartoszherba** [comment]
@sequensucks There are still conflicts.

**Comment by sequensucks** [comment]
i synchronized a fork and merged into my branch.

**Comment by bartoszherba** [comment]
@sequensucks How's going on solving conflicts?

**Comment by sequensucks** [comment]
@bartoszherba  i don't know where is a problem=(
i haven't conflicts.
I clicked a sync a fork (develop branch).
and merged a develop to my branch. Got up to date and nothing to merged.
Github is saying 
image
