### PR TITLE
fix(theme): fix infinite request loop when adding single quantity product

### LINKED ISSUE #686: [Category] Adding product to cart triggers infinite request loop
### Expected result
Product is added to cart

### Actual result
Clicking add to cart button triggers infinite request loop

### PR DESCRIPTION
**Pull request by ghost**
Fix bug introduced in #681 where quantity would not be sent (undefined) - overlooked the extra $event back when I was reviewing that one (should be in just the horizontal card, not in both)

Fixes #686 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/theme/pages/Category.vue [hunk 1]
```diff
@@ -78,7 +78,7 @@
               :wishlist-icon="isAuthenticated ? 'heart' : ''"
               class="products__product-card"
               @click:wishlist="addItemToWishlist(product)"
-              @click:add-to-cart="addItemToCart({ product, quantity: $event })"
+              @click:add-to-cart="addItemToCart({ product, quantity: 1 })"
```
Comment (Frodigo) [inline packages/theme/pages/Category.vue:81]: but what in case if the user wants to add more than 1 item to the cart?

**Review by RetroModernDev — CHANGES_REQUESTED** [review]

File: packages/theme/pages/Category.vue (hunk 1 above)
Comment (sethidden) [reply packages/theme/pages/Category.vue:81]: This is for the simple "add to cart" card 
obraz

The SfCardHorizontal below has $event
obraz

Comment (Frodigo) [reply packages/theme/pages/Category.vue:81]: I see, thanks!

**Review by RetroModernDev — APPROVED** [review]
