### PR TITLE
fix: getAvailableShippingMethods query variables

### LINKED ISSUE #1264: [Bug]: Wrong params in getAvailableShippingMethods
### Expected Behavior

_No response_

### Actual Behavior

wait for input cartId
but use in the query $cart_id

https://github.com/vuestorefront/magento2/blob/3c3c483e0b801f70ef096a1b9d0d87301d919e8c/packages/api-client/src/api/getAvailableShippingMethods/index.ts:14

https://github.com/vuestorefront/magento2/blob/3c3c483e0b801f70ef096a1b9d0d87301d919e8c/packages/api-client/src/api/getAvailableShippingMethods/GuestAvailableShippingMethods.ts:4

### Possible Solution

_No response_

### Steps to reproduce

_No response_

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

v16.12.0

### What browser (and version) are you using?

Chrome Version 94.0.4606.71 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS Version 11.6 (20G165)

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sequensucks**
Replace a cart_id getAvailableShippingMethods query variable with a cartId

fix #1264

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: packages/api-client/src/api/getAvailableShippingMethods/GuestAvailableShippingMethods.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import gql from 'graphql-tag';
 
 export default gql`
-  query GuestAvailableShippingMethods($cart_id: String!) {
+  query GuestAvailableShippingMethods($cartId: String!) {
     cart(cart_id:$cart_id) {
```
Comment (Frodigo) [inline packages/api-client/src/api/getAvailableShippingMethods/GuestAvailableShippingMethods.ts:5]: Once you changed `$cart_id` to `$cartId`, you need to change it here: `cart_id:$cartId`

**Review by Frodigo — CHANGES_REQUESTED** [review]

**Comment by filrak** [comment]
Thanks for your contribution @sequensucks!

**Review by Frodigo — APPROVED** [review]
